# TwelveData (800/giorno)
TWELVEDATA_KEY = "df45281e4b304df8854da7c517392e21"

# Alpha Vantage (25/giorno)
ALPHA_VANTAGE_KEY = "O2MEU23NZEWUYTKY"

# Marketaux (100/giorno)
MARKETAUX_TOKEN = "YlYc82Kl01CnleIi0fYPiyz1paMLVl0kgUSgrjbK"

# Telegram (opzionale)
TELEGRAM_BOT_TOKEN = "tuo_token_telegram"
TELEGRAM_CHAT_ID = "tuo_chat_id_telegram"

# Finnhub (60 chiamate/minuto) - SOSTITUISCE POLYGON
FINNHUB_KEY = "d6i7vf9r01ql9cif9t90d6i7vf9r01ql9cif9t9g"
