# Inserisci le tue API keys qui
MARKETAUX_TOKEN = "YlYc82Kl01CnleIi0fYPiyz1paMLVl0kgUSgrjbK"
TWELVEDATA_KEY = "df45281e4b304df8854da7c517392e21"
ALPHA_VANTAGE_KEY = "O2MEU23NZEWUYTKY"
POLYGON_KEY = "iJwfHevDu1chYz32HlzH0v9lL3PWtQfP"
TELEGRAM_BOT_TOKEN = "tuo_token_telegram"
TELEGRAM_CHAT_ID = "tuo_chat_id_telegram"

